timetable/table/urls.py
from django.conf.urls import url
from . import views

# https://docs.djangoproject.com/en/1.10/intro/tutorial03/

app_name = 'table'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^(\w+)/$', views.index, name='index')
]

timetable/timetable/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^table/', include('table.urls')),
]

timetable/table/models.py
from __future__ import unicode_literals

import datetime
from django.db import models
from django.utils import timezone


class Program(models.Model):
    title = models.CharField(max_length=50)

    def __str__(self):
        return self.title


class Course(models.Model):
    code = models.CharField(max_length=9)
    name = models.CharField(max_length=100)
    programs = models.ManyToManyField(Program)

    def __str__(self):
        return self.code


class Master(models.Model):
    course_code = models.CharField(max_length=8)
    cl_no = models.CharField(max_length=4)
    course_name = models.CharField(max_length=100)
    cl_day = models.IntegerField()
    cl_start_time = models.TimeField()
    cl_end_time = models.TimeField()
    cl_room = models.CharField(max_length=10)
    lecturer = models.CharField(max_length=20)

    def __str__(self):
        return '{}-{}'.format(self.course_code, self.cl_no)

timetable/table/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from .models import Master, Program, Course
from django.shortcuts import redirect
from django import forms

dict = {'day': 'cl_day', 'code': 'course_code', 'cl_no': 'cl_no'}


def home(request):
    return redirect('/table/all')


def index(request, prog_name):
    queries = request.GET.lists()

    if prog_name == 'all':
        course_list = Master.objects.values_list('course_code', flat=True).distinct()
    else:
        course_list = [course.code for course in Course.objects.filter(programs__title=prog_name)]

    # Need to fix this later. Switched to python3 now idk what to do.
    _queries = list(queries)
    if len(_queries)== 0:
        class_list = Master.objects.filter(course_code__in=course_list)
    else:
        kwargs = {}
        for key, arg in _queries:
            if key == 'venue':
                kwargs[dict[key] + '__in'] = arg
            kwargs[dict[key]+'__in'] = arg
            class_list = Master.objects.filter(course_code__in=course_list).filter(**kwargs)

    class FilterForm(forms.Form):
        DAYS = (('1', 'Mon'),
                ('2', 'Tue'),
                ('3', 'Wed'),
                ('4', 'Thr'),
                ('5', 'Fri'),
                ('6', 'Sat'))
        VENUE = (('1', 'KEC'),
                 ('2', 'CIT'))
        day = forms.ChoiceField(label='', widget=forms.SelectMultiple(attrs={'id': 'dayFilter'}), choices=DAYS)

        ahh = [(course_code, Course.objects.get(code=course_code).name) for course_code in course_list]

        # Lol dafuq? I dunno how to use lamba! All hail stackoverflow! lololol
        avail_course = sorted(ahh, key=lambda tup: tup[1])
        code = forms.ChoiceField(label='', widget=forms.SelectMultiple(attrs={'id': 'courseFilter'}),
                                 choices=avail_course)

    form = FilterForm()
    form.fields['day'].initial = request.GET.getlist('day', default=[1,2,3,4,5,6])
    form.fields['code'].initial = request.GET.getlist('code', default=course_list)

    context = {'class_list': class_list,
               'filterForm': form,
               'prog_name': prog_name}

    return render(request, 'table/index.html', context)

def name(request, name):
    context = {'name': name}
    return render(request, 'table/name.html', context)

timetable/table/templates/table/detail.html
{% load staticfiles %}

<html>
<head>
    <link rel="stylesheet" href="{% static 'table/bootstrap.css' %}">
</head>


<h1>{{ question.question_text }}</h1>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'table:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice"
               id="choice{{ forloop.counter }}"
               value="{{ choice.id }}" />
        <label for="choice{{ forloop.counter }}">
            {{ choice.choice_text }}
        </label>
        <br />
    {% endfor %}
    <input type="submit" value="Vote" />
</form>

</html>

timetable/table/templates/table/index.html
{% load static %}
<html>
<head>
    <!--<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs-3.3.7/dt-1.10.13/b-1.2.4/r-2.1.0/datatables.min.css"/>-->
    <link rel="stylesheet" type="text/css" href="{% static 'table/style.css' %}"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.13/css/bootstrap-multiselect.css" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.13/css/jquery.dataTables.css">-->
</head>

<div class="container-fluid">
<body>
<div class="page-header"><h2>Master Timetable for {{ prog_name }}</h2></div>

<form method="GET">
    <div class="form-group">
         <div class="btn-group">
              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                Program: {{ prog_name }} <span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <li><a href="{% url 'table:index' 'AEng' %}">AEng Yr 1</a></li>
                <li><a href="{% url 'table:index' 'ASci' %}">ASci Yr 1</a></li>
                <li><a href="{% url 'table:index' 'ASoSci' %}">ASoSci Yr 1</a></li>
                <li><a href="{% url 'table:home' %}">All Programs (maybe slow, I dunno)</a></li>
              </ul>
         </div>
        {{ filterForm }}
        <button type="submit" class="btn btn-primary">Apply</button>
        <a href="{% url 'table:index' prog_name %}" class="btn btn-danger">Clear All</a>
    </div>
</form>





<table id="timetable" class="table table-striped table-condensed table-responsive table-bordered">
    <thead>
        <tr>
            <!--<th>Course Code</th>-->
            <th>Class</th>
            <th>Course Name</th>
            <th>Day</th>
            <th>Start</th>
            <th>End</th>
            <th>Room</th>
            <th>Lecturer</th>
        </tr>
    </thead>
    <tbody>
    {% for cl in class_list %}
        <tr>
            <!--<td>{{ cl.course_code }}</td>-->
            <td>{{ cl.cl_no }}</td>
            <td>{{ cl.course_name }}</td>
            <td align="center">{{ cl.cl_day }}</td>
            <td>{{ cl.cl_start_time|time:"H:i" }}</td>
            <td>{{ cl.cl_end_time|time:"H:i" }}</td>
            <td>{{ cl.cl_room }}</td>
            <td>{{ cl.lecturer }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>






<script
  src="https://code.jquery.com/jquery-3.1.1.js"
  integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA="
  crossorigin="anonymous"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/bs-3.3.7/dt-1.10.13/b-1.2.4/r-2.1.0/datatables.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.13/js/bootstrap-multiselect.min.js"></script>
<!--<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.13/js/jquery.dataTables.js"></script>-->
<script src="{% static 'table/script.js' %}"></script>
</body>
</div>
</html>

timetable/table/templates/table/name.html
<h1>{{ name }}</h1>

timetable/table/templates/table/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'table:detail' question.id %}">Vote again?</a>